---
title: "Model Selection"
author: "Madelynn Smith"
date: "2025-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(readxl, dplyr, lubridate, ggplot2, scales, ggcorrplot, maps, rpart, rpart.plot)

```

```{r loading data}
Data <- read_excel("/Users/madelynnjoan/Desktop/FDAcleaned.xlsx") %>% 

        ###CODING STATES BASED ON REGIONS
        mutate(region_code = case_when(
        # 0 = NORTHEAST
        state %in% c("Maine","New Hampshire","Vermont","Massachusetts","Rhode Island","Connecticut", "New York","New Jersey","Pennsylvania", "District of Columbia") ~ 0,
        # 1 = SOUTHEAST
        state %in% c("Delaware","Maryland","District of Columbia","Virginia","West Virginia",
                 "Kentucky","Tennessee","North Carolina","South Carolina","Georgia",
                 "Florida","Alabama","Mississippi","Arkansas","Louisiana", "Puerto Rico") ~ 1,
        # 2 = MIDWEST
        state %in% c("Ohio","Michigan","Indiana","Illinois","Wisconsin","Minnesota","Iowa",
                 "Missouri","North Dakota","South Dakota","Nebraska","Kansas") ~ 2,

        # 3 = SOUTHWEST
        state %in% c("Texas","Oklahoma","New Mexico","Arizona") ~ 3,

        # 4 = WEST
        state %in% c("Colorado","Wyoming","Montana","Idaho","Utah","Nevada","Washington",
                 "Oregon","California","Alaska","Hawaii") ~ 4)) %>% 
  
        #####CODING EVENT AND PRODUCT CLASSIFICATION
        mutate(class_code_product = case_when(
               product_classification == "Class I" ~ 1,
               product_classification == "Class II" ~ 2,
               product_classification == "Class III" ~ 3,
                TRUE ~ NA_real_)) %>% 

        mutate(class_code_event = case_when(
               event_classification == "Class I" ~ 1,
               event_classification == "Class II" ~ 2,
               event_classification == "Class III" ~ 3,
                TRUE ~ NA_real_)) %>% 
      
      ##product type dummy variable
      mutate(product_type_code = case_when(
               product_type == "Biologics" ~ 0,
               product_type == "Devices" ~ 1,
               product_type == "Drugs" ~ 2,
               product_type == "Food/Cosmetics" ~ 3,
               product_type == "Tobacco" ~ 4,
               product_type == "Veterinary" ~ 5,
              TRUE ~ NA_real_)) %>% 
  
    ##center dummy variable
      mutate(center_code = case_when(
               center == "CBER" ~ 0,
               center == "CDER" ~ 1,
               center == "CDRH" ~ 2,
               center == "CFSAN" ~ 3,
               center == "CTP" ~ 4,
               center == "CVM" ~ 5,
               center == "HFP" ~ 5,
               center == "OCS" ~ 5,
              TRUE ~ NA_real_)) %>% 

    ##status dummy variable
      mutate(status_code = case_when(
               status == "Completed" ~ 0,
               status == "Ongoing" ~ 1,
               status == "Terminated" ~ 2,
              TRUE ~ NA_real_)) %>% 
  ##seasons variable
      mutate(recall_date = mdy(recall_date), # convert to proper Date
              month = month(recall_date),   # extract month number (1–12)
    season = case_when(                      # assign seasons
      month %in% c(12, 1, 2)  ~ "Winter",
      month %in% c(3, 4, 5)   ~ "Spring",
      month %in% c(6, 7, 8)   ~ "Summer",
      month %in% c(9, 10, 11) ~ "Fall"
    )
  )

```


Improved Descision Tree
```{r tree final}
#only using class I, rather than separating all three classes at once

Data$ClassI <- ifelse(Data$event_classification == "Class I", "Yes", "No")
Data$ClassI <- factor(Data$ClassI)

tree_model_final <- rpart(ClassI ~ product_type + status + center + region_code + season, 
                          data = Data,
                          method = "class",   #controlling complexity
                          cp = 0.01,          # higher = simpler tree
                          minsplit = 20,      # fewer tiny branches
                          maxdepth = 5)
#finding best cp
printcp(tree_model_final)
plotcp(tree_model_final)

pruned <- prune(tree_model_final, cp = tree_model_final$cptable[which.min(tree_model_final$cptable[,"xerror"]), "CP"])

rpart.plot(pruned, type = 3, extra = 104, fallen.leaves = TRUE)
```

```{r model framework}
nrow(Data)
ncol(Data)

```

