---
title: "Exploratory Data Analysis - Public Health"
author: "Madelynn Smith"
date: "2025-10-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(readxl, dplyr, lubridate, ggplot2, scales, ggcorrplot, maps)
```

Loading Data, creating dummy variables for US regions, product type, center, product classification, and event classification

```{r loading data}
Data <- read_excel("/Users/madelynnjoan/Desktop/FDAcleaned.xlsx") %>% 
        
        ###CODING STATES BASED ON REGIONS
        mutate(region_code = case_when(
        # 0 = NORTHEAST
        state %in% c("Maine","New Hampshire","Vermont","Massachusetts","Rhode Island","Connecticut", "New York","New Jersey","Pennsylvania", "District of Columbia") ~ 0,
        # 1 = SOUTHEAST
        state %in% c("Delaware","Maryland","District of Columbia","Virginia","West Virginia",
                 "Kentucky","Tennessee","North Carolina","South Carolina","Georgia",
                 "Florida","Alabama","Mississippi","Arkansas","Louisiana", "Puerto Rico") ~ 1,
        # 2 = MIDWEST
        state %in% c("Ohio","Michigan","Indiana","Illinois","Wisconsin","Minnesota","Iowa",
                 "Missouri","North Dakota","South Dakota","Nebraska","Kansas") ~ 2,

        # 3 = SOUTHWEST
        state %in% c("Texas","Oklahoma","New Mexico","Arizona") ~ 3,

        # 4 = WEST
        state %in% c("Colorado","Wyoming","Montana","Idaho","Utah","Nevada","Washington",
                 "Oregon","California","Alaska","Hawaii") ~ 4)) %>% 
  
        #####CODING EVENT AND PRODUCT CLASSIFICATION
        mutate(class_code_product = case_when(
               product_classification == "Class I" ~ 1,
               product_classification == "Class II" ~ 2,
               product_classification == "Class III" ~ 3,
                TRUE ~ NA_real_)) %>% 

        mutate(class_code_event = case_when(
               event_classification == "Class I" ~ 1,
               event_classification == "Class II" ~ 2,
               event_classification == "Class III" ~ 3,
                TRUE ~ NA_real_)) %>% 
      
      ##product type dummy variable
      mutate(product_type_code = case_when(
               product_type == "Biologics" ~ 0,
               product_type == "Devices" ~ 1,
               product_type == "Drugs" ~ 2,
               product_type == "Food/Cosmetics" ~ 3,
               product_type == "Tobacco" ~ 4,
               product_type == "Veterinary" ~ 5,
              TRUE ~ NA_real_)) %>% 
  
    ##center dummy variable
      mutate(center_code = case_when(
               center == "CBER" ~ 0,
               center == "CDER" ~ 1,
               center == "CDRH" ~ 2,
               center == "CFSAN" ~ 3,
               center == "CTP" ~ 4,
               center == "CVM" ~ 5,
               center == "HFP" ~ 5,
               center == "OCS" ~ 5,
              TRUE ~ NA_real_)) %>% 

    ##status dummy variable
      mutate(status_code = case_when(
               status == "Completed" ~ 0,
               status == "Ongoing" ~ 1,
               status == "Terminated" ~ 2,
              TRUE ~ NA_real_)) %>% 
  ##seasons variable
      mutate(recall_date = mdy(recall_date), # convert to proper Date
              month = month(recall_date),   # extract month number (1–12)
    season = case_when(                      # assign seasons
      month %in% c(12, 1, 2)  ~ "Winter",
      month %in% c(3, 4, 5)   ~ "Spring",
      month %in% c(6, 7, 8)   ~ "Summer",
      month %in% c(9, 10, 11) ~ "Fall"
    )
  )

```


1) Univariate Analysis
```{r univariate analysis distinct values}
n_distinct(Data$FEI.Number)

Data %>%
  summarise(across(c(FEI.Number, firm, product_type, product_classification, status,                      distribution, state, recall_date, reason, product_description,                      event_id, event_classification, product_id, center),                                n_distinct))

sort(table(Data$FEI.Number), decreasing = TRUE)[1:5]
sort(table(Data$firm), decreasing = TRUE)[1:5]
sort(table(Data$product_type), decreasing = TRUE)[1:5]
sort(table(Data$product_classification), decreasing = TRUE)[1:5]
sort(table(Data$status), decreasing = TRUE)[1:5]
sort(table(Data$distribution), decreasing = TRUE)[1:5]
sort(table(Data$state), decreasing = TRUE)[1:5]
sort(table(Data$recall_date), decreasing = TRUE)[1:5]
sort(table(Data$reason), decreasing = TRUE)[1:5]
sort(table(Data$product_description), decreasing = TRUE)[1:5]
sort(table(Data$event_id), decreasing = TRUE)[1:5]
sort(table(Data$event_classification), decreasing = TRUE)[1:5]
sort(table(Data$product_id), decreasing = TRUE)[1:5]
sort(table(Data$center), decreasing = TRUE)[1:5]

##details for paragraphs 
table(Data$product_type)
table(Data$state)
```

2) Pattern Analysis (specifically time series)
```{r time series}
Data$recall_date <- as.Date(Data$recall_date, format = "%m/%d/%Y")

##Data for recalls by month (plotted point every month)
Data_monthly <- Data %>%
  mutate(month = floor_date(recall_date, "month")) %>%
  group_by(month) %>%
  summarise(count = n())

ggplot(Data_monthly, aes(x = month, y = count)) +
  geom_line() +
  labs(title = "Monthly FDA Recalls Over Time",
       x = "Month",
       y = "Number of Recalls")


##Data for recalls by month and event classification (to facet wrap)
Data_monthly_classification <- Data %>%
  mutate(month = floor_date(recall_date, "month")) %>%
  group_by(month, event_classification) %>%
  summarise(count = n())

ggplot(Data_monthly_classification, aes(x = month, y = count)) +
  geom_line() +
  labs(title = "Monthly FDA Recalls Over Time by Event Classification",
       x = "Month",
       y = "Number of Recalls") +
  facet_wrap(~event_classification)
  ###scale_x_discrete(date_breaks = "6 months", date_labels = "%b %Y") 
```

1) Variable Analysis -- Bivariate Analysis
```{r bivariate correllation plot}
Data_corrplot1 <- Data %>%
  select(region_code, class_code_product, class_code_event, product_type_code, center_code, status_code)

corr_matrix1 <- cor(Data_corrplot1, use = "complete.obs")
corr_matrix1

#correlation heatmap
Data_sub <- Data_corrplot1 %>%
  filter(!is.na(region_code) & !is.na(class_code_product) & !is.na(class_code_event) & !is.na(product_type_code) & !is.na(center_code) & !is.na(status_code))

#variable structure
str(Data_sub)

#correlation matrix
cor_matrix <- cor(Data_sub, use = "complete.obs")
cor_matrix

# Plot heatmap
ggcorrplot(
  cor_matrix,
  method = "square",
  type = "full",
  lab = TRUE,
  lab_size = 4,
  colors = c("blue", "white", "red"),
  title = "Correlation Heatmap",
  ggtheme = theme_minimal()
)



##Heatmap 1 
heat_data1 <- Data %>%
  count(region_code, class_code_event)

# plot
ggplot(heat_data1, aes(x = factor(region_code),
                      y = factor(class_code_event),
                      fill = n)) +
  geom_tile(color = "white") +
  geom_text(aes(label = n), color = "white", size = 3) +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  labs(title = "Heatmap of Recall Counts by Region and Event Classification",
       x = "Region Code", y = "Event Classification",
       fill = "Count") +
  theme_minimal()

heat_data2 <- Data %>%
  count(product_type, class_code_event)

# plot
ggplot(heat_data2, aes(x = factor(product_type),
                      y = factor(class_code_event),
                      fill = n)) +
  geom_tile(color = "white") +
  geom_text(aes(label = n), color = "white", size = 3) +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  labs(title = "Heatmap of Recall Counts by Product and Event Classification",
       x = "Product", y = "Event Classification",
       fill = "Count") +
  theme_minimal()

heat_data3 <- Data %>%
  count(center, class_code_event)

# plot
ggplot(heat_data3, aes(x = factor(center),
                      y = factor(class_code_event),
                      fill = n)) +
  geom_tile(color = "white") +
  geom_text(aes(label = n), color = "white", size = 3) +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  labs(title = "Heatmap of Recall Counts by Center and Event Classification",
       x = "Center", y = "Event Classification",
       fill = "Count") +
  theme_minimal()


```


3) VIZUALIZATIONS

Vizualization Number 1 -- ADVANCED
```{r advanced vizualization}
##advanced vizualization 1 
us_map <- map_data("state")

state_counts <- Data %>%
  count(state, name = "total_recalls") %>%
  mutate(region = tolower(state))               

plot_df <- us_map %>%
  left_join(state_counts, by = "region")

ggplot(plot_df, aes(long, lat, group = group, fill = total_recalls)) +
  geom_polygon(color = "white", linewidth = 0.2) +
  coord_map("albers", lat0 = 39, lat1 = 45) +
  scale_fill_gradient(low = "lightblue", high = "darkblue",
                      na.value = "grey90", name = "Total Recalls") +
  labs(title = "Total Recalls by State") +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.text  = element_blank(),
        panel.grid = element_blank())

##advanced visualization 2
Data %>%
  count(class_code_product, season) %>%           # count recalls per class + season
  group_by(class_code_product) %>%                # group within each class
  mutate(prop = n / sum(n)) %>%                   # convert to proportions
  ggplot(aes(x = as.factor(class_code_product),
             y = prop,
             fill = season)) +
  geom_col() +
  labs(
    title = "Proportion of FDA Recalls by Event Class and Season",
    x = "Event Classification (Class)",
    y = "Proportion of Recalls",
    fill = "Season"
  ) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "right"
  )

```

Vizualization Number 2 -- bar chart

```{r vizualization - bar chart}

ggplot(Data, aes(x = factor(region_code))) +
  geom_bar(fill = "maroon", color = "black") +
  labs(title = "Number of Recalls by Region",
       x = "Region Code",
       y = "Count of Recalls") +
  theme_minimal()

ggplot(Data, aes(x = factor(product_type))) +
  geom_bar(fill = "maroon", color = "black") +
  labs(title = "Number of Recalls by Product Type",
       x = "Product Type",
       y = "Count of Recalls") +
  theme_minimal()
```